### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'unable to udp ping: 

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#6]
Running `crusader test <host>` on macOS 12.6.1 laptop on Wi-Fi to small odroid running `crusader serve` on Ethernet with Ubuntu 20.04.05. I got the following error messages the very first three times I ran it after compiling it (on macOS).

```
√ release % ./crusader test 192.168.253.128
Connected to server 192.168.253.128:35481
Latency to server 2.69 ms
Testing download...
Testing upload...
thread 'tokio-runtime-worker' panicked at 'unable to udp ping: Os { code: 55, kind: Uncategorized, message: "No buffer space available" }', crusader-lib/src/test.rs:1232:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      ./crusader test 192.168.253.128
?134 release % ./crusader test 192.168.253.128
Connected to server 192.168.253.128:35481
Latency to server 2.62 ms
Testing download...
Testing upload...
Testing both download and upload...
thread 'tokio-runtime-worker' panicked at 'unable to udp ping: Os { code: 55, kind: Uncategorized, message: "No buffer space available" }', crusader-lib/src/test.rs:1232:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      ./crusader test 192.168.253.128
?134 release % ./crusader test 192.168.253.128
Connected to server 192.168.253.128:35481
Latency to server 2.63 ms
Testing download...
Testing upload...
Testing both download and upload...
Writing data...
Saved raw data as data 2022.12.06 21-00-02.crr
Saved plot as plot 2022.12.06 21-00-02.png
√ release %
```

**Server said...**

```
llladmin@odroid:~/Documents/src/crusader/src/target/release$ ./crusader serve
Server running...
Serving 192.168.253.116:50773, version 3
Error from client 192.168.253.116:50773: Connection reset by peer (os error 104)
Serving 192.168.253.116:50859, version 3
Error from client 192.168.253.116:50859: Connection reset by peer (os error 104)
Serving 192.168.253.116:50929, version 3
Serving complete for 192.168.253.116:50929
^CServer aborting...
```

**Plot (from third run)** Not sure if this is good or bad...

![plot 2022 12 06 21-00-02](https://user-images.githubusercontent.com/1094930/206070034-9356a07e-41df-4f21-8f09-52d68e74a3d8.png)

**Comment by Fail-Safe** [comment]
Just gave crusader a try after recommendation by @dtaht. On MacOS 14.2.1, I am seeing the same crash (identical details as above) as well.

FWIW, I also tried to execute the MacOS client with `sudo`, thinking that the application might need additional permissions to lower-level socket functions, but was met with the same error.

```zsh
❯ sudo RUST_BACKTRACE=full ./crusader test 192.168.45.5
Connected to server 192.168.45.5:35481
Latency to server 2.42 ms
Testing download...
Testing upload...
thread 'tokio-runtime-worker' panicked at 'unable to udp ping: Os { code: 55, kind: Uncategorized, message: "No buffer space available" }', crusader-lib/src/test.rs:1232:32
stack backtrace:
   0:        0x10102dab4 - __mh_execute_header
   1:        0x1010491ab - __mh_execute_header
   2:        0x101028328 - __mh_execute_header
   3:        0x10102efdd - __mh_execute_header
   4:        0x10102ed34 - __mh_execute_header
   5:        0x10102f518 - __mh_execute_header
   6:        0x10102f453 - __mh_execute_header
   7:        0x10102df37 - __mh_execute_header
   8:        0x10102f12a - __mh_execute_header
   9:        0x10105d783 - __mh_execute_header
  10:        0x10105d875 - __mh_execute_header
  11:        0x100f1ee2d - __mh_execute_header
  12:        0x100ec5ea2 - __mh_execute_header
  13:        0x100fbc7a2 - __mh_execute_header
  14:        0x100fb5c8c - __mh_execute_header
  15:        0x100fb4e5e - __mh_execute_header
  16:        0x100fb4735 - __mh_execute_header
  17:        0x100fbc4c8 - __mh_execute_header
  18:        0x100fa01a0 - __mh_execute_header
  19:        0x100fac6cd - __mh_execute_header
  20:        0x100fa0f65 - __mh_execute_header
  21:        0x100fa14c6 - __mh_execute_header
  22:        0x101031fc7 - __mh_execute_header
  23:     0x7ff80165f202 - __pthread_start
[1]    11512 abort      sudo RUST_BACKTRACE=full ./crusader test 192.168.45.5
```

**Comment by Zoxc** [comment]
I attempted a workaround for this in [v0.0.10](https://github.com/Zoxc/crusader/releases/tag/v0.0.10-testing). Can you reproduce it with that?

**Comment by Fail-Safe** [comment]
Looks like we're in business now! @richb-hanover Are you seeing success with the new release as well?

![image](https://github.com/Zoxc/crusader/assets/10307870/e80f772b-7b9d-4e40-a453-6bce7f801408)

**Comment by dtaht** [comment]
yep. And see how weird the up+down test is? What's the link?

**Comment by richb-hanover** [comment]
I can confirm that it's working fine (server, CLI version, and crusader-gui) on my computer. Thanks!
