### ISSUE TITLE
Better error message when no graphic subsystem available?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#60]
I mistakenly invoked `crusader-gui` on my headless RPi4. I got the following error message. Nothing bad happened, and I quickly realized what I did wrong.

But I wonder if there could be a better error message, such as: "Error starting GUI - is a graphic subsystem available?" Thanks.
```
deploy@rpi4:~/src/crusader/src/target/release$ ./crusader-gui
thread 'main' panicked at crusader-gui/src/main.rs:85:6:
called `Result::unwrap()` on an `Err` value: WinitEventLoop(Os(OsError { line: 786, file: "/home/deploy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set.") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by richb-hanover** [comment]
With crusader 0.2.1-dev (commit 8de48276cfe337e58857acad8c674be67bf2e447), `crusader-gui` displays:

```
deploy@RPi5:~/Documents/src/crusader/src/target/release$ ./crusader-gui
Failed to run GUI: winit EventLoopError: os error at /home/deploy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:786: neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set.
```
Thanks. Closing
